<?php

namespace Database\Seeders;

use App\Models\BlogPost;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class BlogPostSeeder extends Seeder
{
    public function run(): void
    {
        $posts = [
            [
                'title' => '5 Key Strategies for Optimizing Your Supply Chain in 2026',
                'slug' => 'optimizing-supply-chain-2026',
                'category' => 'STRATEGY',
                'author' => 'Ahmed Al Mansoori',
                'published_at' => Carbon::parse('2026-02-10'),
                'read_time' => '8 min read',
                'image' => 'https://images.unsplash.com/photo-1592085198739-ffcad7f36b54?q=80&w=1080',
                'intro' => 'As global trade dynamics shift, supply chain optimization has become more than just a cost-saving measure—it is a critical competitive advantage for businesses operating in the MENA region.',
                'conclusion' => 'Optimizing your supply chain in 2026 requires a balanced approach of technological adoption and strategic risk management. Al Zaha remains committed to guiding our partners through these complexities with executive-level precision.',
                'content' => [
                    ['type' => 'h2', 'text' => '1. Leveraging Artificial Intelligence for Demand Forecasting'],
                    ['type' => 'p', 'text' => 'The landscape of supply chain management is undergoing a seismic shift driven by AI. In 2026, predictive analytics is no longer a luxury but a necessity. By analyzing historical data and market trends, AI helps companies anticipate demand fluctuations with unprecedented accuracy.'],
                    ['type' => 'image', 'src' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1080'],
                    ['type' => 'p', 'text' => 'Implementing AI-driven solutions allows Al Zaha to provide clients with real-time visibility into their procurement cycles, reducing lead times and minimizing the risk of overstocking or stockouts in a volatile market.'],
                    ['type' => 'h2', 'text' => '2. Diversifying Supplier Networks'],
                    ['type' => 'p', 'text' => 'Geopolitical stability remains a primary concern for international trade. Relying on a single sourcing origin is a risk that modern enterprises cannot afford. Diversification ensures that disruptions in one region do not paralyze the entire operation.'],
                    ['type' => 'blockquote', 'text' => 'Resilience is built through redundancy. A robust supply chain is one that can pivot instantly when traditional routes or sources are compromised.'],
                    ['type' => 'p', 'text' => 'Our approach at Al Zaha emphasizes a multi-hub sourcing model, utilizing Dubai as a central node while maintaining strong partnerships across Asia, Europe, and Africa.'],
                    ['type' => 'image', 'src' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1080'],
                    ['type' => 'h2', 'text' => '3. Sustainable Logistics and Carbon Footprint Reduction'],
                    ['type' => 'p', 'text' => 'Sustainability is now a core pillar of corporate responsibility in the UAE. Green logistics—ranging from electric transport fleets to optimized shipping routes—reduces both environmental impact and operational costs over the long term.'],
                ],
            ],
            [
                'title' => 'How to Choose the Right Sourcing Partner for Industrial Projects',
                'slug' => 'choosing-sourcing-partner',
                'category' => 'SOURCING',
                'author' => 'Sarah Chen',
                'published_at' => Carbon::parse('2026-02-05'),
                'read_time' => '6 min read',
                'image' => 'https://images.unsplash.com/photo-1763926026024-2b294669e255?q=80&w=1080',
                'intro' => 'Selecting a sourcing partner is one of the most consequential decisions an industrial firm can make. A wrong choice leads to quality issues, delays, and financial loss.',
                'conclusion' => "The right partner doesn't just find products; they build the foundation of your production capability.",
                'content' => [
                    ['type' => 'h2', 'text' => 'Due Diligence Beyond the Balance Sheet'],
                    ['type' => 'p', 'text' => 'Technical competency is only the baseline. A true partner must demonstrate cultural alignment, ethical standards, and a proven track record in your specific industry vertical.'],
                    ['type' => 'image', 'src' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=1080'],
                    ['type' => 'p', 'text' => 'At Al Zaha, we conduct rigorous on-site audits and quality control checks to ensure every supplier meets our stringent premium standards before they ever enter our network.'],
                    ['type' => 'blockquote', 'text' => 'The cheapest price is often the most expensive cost. Value in sourcing is found at the intersection of quality, reliability, and total landed cost.'],
                    ['type' => 'h2', 'text' => 'Transparency in Communication'],
                    ['type' => 'p', 'text' => 'In complex industrial projects, communication gaps are fatal. Your sourcing partner should act as a seamless extension of your procurement department, providing honest updates even when things go wrong.'],
                ],
            ],
            [
                'title' => 'Understanding Logistics Costs: A Complete Breakdown for Dubai Businesses',
                'slug' => 'logistics-costs-breakdown',
                'category' => 'LOGISTICS',
                'author' => 'Marcus Weber',
                'published_at' => Carbon::parse('2026-01-28'),
                'read_time' => '10 min read',
                'image' => 'https://images.unsplash.com/photo-1725449264087-28926bc1a610?q=80&w=1080',
                'intro' => 'Logistics costs can often remain opaque, hidden within "all-in" quotes. For businesses in Dubai, understanding the granular breakdown is key to unlocking efficiency.',
                'conclusion' => 'A transparent breakdown allows for data-driven decisions that impact the bottom line directly.',
                'content' => [
                    ['type' => 'h2', 'text' => 'The Core Components of Landed Cost'],
                    ['type' => 'p', 'text' => 'From terminal handling charges to last-mile delivery, every step in the logistics chain incurs costs that can be optimized through better route planning and consolidation.'],
                    ['type' => 'image', 'src' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1080'],
                    ['type' => 'h2', 'text' => 'Optimizing Warehousing and Storage'],
                    ['type' => 'p', 'text' => 'Inventory carrying costs are often underestimated. By utilizing JIT (Just-In-Time) delivery models, Dubai firms can reduce their warehouse footprint and free up working capital.'],
                ],
            ],
            [
                'title' => 'The Future of Procurement: Digital Transformation in the UAE',
                'slug' => 'future-procurement-digital',
                'category' => 'INSIGHTS',
                'author' => 'Al Zaha Editorial Team',
                'published_at' => Carbon::parse('2026-02-14'),
                'read_time' => '5 min read',
                'image' => 'https://images.unsplash.com/photo-1765020553734-2c050ddb9494?q=80&w=1080',
                'intro' => 'Digital transformation is reshaping procurement across the UAE and the wider region.',
                'conclusion' => 'Contact Al Zaha to learn how we can support your digital procurement journey.',
                'content' => [
                    ['type' => 'h2', 'text' => 'Identifying Operational Inefficiencies'],
                    ['type' => 'p', 'text' => 'Modern business environments require a proactive approach to identifying bottlenecks before they impact production or delivery schedules.'],
                    ['type' => 'image', 'src' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1080'],
                    ['type' => 'p', 'text' => 'Streamlining processes through digitalization is the first step toward building a resilient framework that can withstand global market pressures.'],
                    ['type' => 'blockquote', 'text' => 'Excellence in the supply chain is not an act, but a habit of continuous improvement and rigorous oversight.'],
                    ['type' => 'h2', 'text' => 'Standardizing Quality Across the Chain'],
                    ['type' => 'p', 'text' => 'Maintaining consistent quality requires clear standards and regular audits across all partners and vendors in the supply network.'],
                ],
            ],
            [
                'title' => 'Why Dubai is the Perfect Hub for Global Sourcing Operations',
                'slug' => 'dubai-global-sourcing-hub',
                'category' => 'INSIGHTS',
                'author' => 'Al Zaha Editorial Team',
                'published_at' => Carbon::parse('2026-02-14'),
                'read_time' => '5 min read',
                'image' => 'https://images.unsplash.com/photo-1768069794857-9306ac167c6e?q=80&w=1080',
                'intro' => 'Dubai offers unique advantages as a global sourcing and logistics hub.',
                'conclusion' => "Partner with Al Zaha to leverage Dubai's strategic position.",
                'content' => [
                    ['type' => 'h2', 'text' => 'Identifying Operational Inefficiencies'],
                    ['type' => 'p', 'text' => 'Modern business environments require a proactive approach to identifying bottlenecks before they impact production or delivery schedules.'],
                    ['type' => 'image', 'src' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1080'],
                    ['type' => 'p', 'text' => 'Streamlining processes through digitalization is the first step toward building a resilient framework that can withstand global market pressures.'],
                    ['type' => 'blockquote', 'text' => 'Excellence in the supply chain is not an act, but a habit of continuous improvement and rigorous oversight.'],
                    ['type' => 'h2', 'text' => 'Standardizing Quality Across the Chain'],
                    ['type' => 'p', 'text' => 'Maintaining consistent quality requires clear standards and regular audits across all partners and vendors in the supply network.'],
                ],
            ],
            [
                'title' => 'Risk Management in Cross-Border Supply Chains',
                'slug' => 'risk-management-supply-chains',
                'category' => 'INSIGHTS',
                'author' => 'Al Zaha Editorial Team',
                'published_at' => Carbon::parse('2026-02-14'),
                'read_time' => '5 min read',
                'image' => 'https://images.unsplash.com/photo-1767972463265-3668dd44bb87?q=80&w=1080',
                'intro' => 'Effective risk management is essential for resilient cross-border supply chains.',
                'conclusion' => 'Our team can help you build a robust risk mitigation strategy.',
                'content' => [
                    ['type' => 'h2', 'text' => 'Identifying Operational Inefficiencies'],
                    ['type' => 'p', 'text' => 'Modern business environments require a proactive approach to identifying bottlenecks before they impact production or delivery schedules.'],
                    ['type' => 'image', 'src' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1080'],
                    ['type' => 'p', 'text' => 'Streamlining processes through digitalization is the first step toward building a resilient framework that can withstand global market pressures.'],
                    ['type' => 'blockquote', 'text' => 'Excellence in the supply chain is not an act, but a habit of continuous improvement and rigorous oversight.'],
                    ['type' => 'h2', 'text' => 'Standardizing Quality Across the Chain'],
                    ['type' => 'p', 'text' => 'Maintaining consistent quality requires clear standards and regular audits across all partners and vendors in the supply network.'],
                ],
            ],
            [
                'title' => 'Warehouse Management Best Practices for Growing Businesses',
                'slug' => 'warehouse-management-practices',
                'category' => 'INSIGHTS',
                'author' => 'Al Zaha Editorial Team',
                'published_at' => Carbon::parse('2026-02-14'),
                'read_time' => '5 min read',
                'image' => 'https://images.unsplash.com/photo-1740914994657-f1cdffdc418e?q=80&w=1080',
                'intro' => 'Best practices in warehouse management can drive efficiency and reduce costs.',
                'conclusion' => 'Al Zaha supports end-to-end logistics and warehousing solutions.',
                'content' => [
                    ['type' => 'h2', 'text' => 'Identifying Operational Inefficiencies'],
                    ['type' => 'p', 'text' => 'Modern business environments require a proactive approach to identifying bottlenecks before they impact production or delivery schedules.'],
                    ['type' => 'image', 'src' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1080'],
                    ['type' => 'p', 'text' => 'Streamlining processes through digitalization is the first step toward building a resilient framework that can withstand global market pressures.'],
                    ['type' => 'blockquote', 'text' => 'Excellence in the supply chain is not an act, but a habit of continuous improvement and rigorous oversight.'],
                    ['type' => 'h2', 'text' => 'Standardizing Quality Across the Chain'],
                    ['type' => 'p', 'text' => 'Maintaining consistent quality requires clear standards and regular audits across all partners and vendors in the supply network.'],
                ],
            ],
            [
                'title' => 'Navigating International Trade Regulations in the MENA Region',
                'slug' => 'international-trade-regulations',
                'category' => 'INSIGHTS',
                'author' => 'Al Zaha Editorial Team',
                'published_at' => Carbon::parse('2026-02-14'),
                'read_time' => '5 min read',
                'image' => 'https://images.unsplash.com/photo-1532635042-a6f6ad4745f9?q=80&w=1080',
                'intro' => 'Understanding regional trade regulations is key to successful international operations.',
                'conclusion' => 'We provide compliance and documentation support for your shipments.',
                'content' => [
                    ['type' => 'h2', 'text' => 'Identifying Operational Inefficiencies'],
                    ['type' => 'p', 'text' => 'Modern business environments require a proactive approach to identifying bottlenecks before they impact production or delivery schedules.'],
                    ['type' => 'image', 'src' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1080'],
                    ['type' => 'p', 'text' => 'Streamlining processes through digitalization is the first step toward building a resilient framework that can withstand global market pressures.'],
                    ['type' => 'blockquote', 'text' => 'Excellence in the supply chain is not an act, but a habit of continuous improvement and rigorous oversight.'],
                    ['type' => 'h2', 'text' => 'Standardizing Quality Across the Chain'],
                    ['type' => 'p', 'text' => 'Maintaining consistent quality requires clear standards and regular audits across all partners and vendors in the supply network.'],
                ],
            ],
            [
                'title' => 'Sustainable Sourcing: Building an Eco-Friendly Supply Chain',
                'slug' => 'sustainable-sourcing-supply-chain',
                'category' => 'INSIGHTS',
                'author' => 'Al Zaha Editorial Team',
                'published_at' => Carbon::parse('2026-02-14'),
                'read_time' => '5 min read',
                'image' => 'https://images.unsplash.com/photo-1770823556202-2eba715a415b?q=80&w=1080',
                'intro' => 'Sustainability is increasingly central to supply chain and sourcing decisions.',
                'conclusion' => 'Explore sustainable sourcing options with Al Zaha.',
                'content' => [
                    ['type' => 'h2', 'text' => 'Identifying Operational Inefficiencies'],
                    ['type' => 'p', 'text' => 'Modern business environments require a proactive approach to identifying bottlenecks before they impact production or delivery schedules.'],
                    ['type' => 'image', 'src' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1080'],
                    ['type' => 'p', 'text' => 'Streamlining processes through digitalization is the first step toward building a resilient framework that can withstand global market pressures.'],
                    ['type' => 'blockquote', 'text' => 'Excellence in the supply chain is not an act, but a habit of continuous improvement and rigorous oversight.'],
                    ['type' => 'h2', 'text' => 'Standardizing Quality Across the Chain'],
                    ['type' => 'p', 'text' => 'Maintaining consistent quality requires clear standards and regular audits across all partners and vendors in the supply network.'],
                ],
            ],
        ];

        foreach ($posts as $data) {
            BlogPost::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
